"""
Convert PADS dataset to nmed2024 CSV + TOML format for Transformer training.

Phase 2: Task-grouped tokens
- Movement data: 132 channels x 976 timesteps -> feature extraction
  -> grouped by (task x location x sensor) = 44 tokens, each 31-dim
- Questionnaire: 30 NMS binary items (categorical)
- Demographics: age, gender, height, weight, handedness
- Total tokens: 44 + 30 + 5 = 79 (vs Phase 1's 4127)
"""

import numpy as np
import pandas as pd
from scipy.signal import welch
from sklearn.model_selection import StratifiedShuffleSplit
import os

# Paths
PADS_ROOT = "C:/Users/shkim/codes/pads-project/project/data"
OUTPUT_DIR = "C:/Users/shkim/codes/nmed2024/data/pads"
TOML_DIR = "C:/Users/shkim/codes/nmed2024/dev/data/toml_files"

# ============================================================
# Feature extraction (reproduced from PADS ml/feature_extraction.py)
# ============================================================

def bandpower(x, srate=100, steps=100, cut=(1, 20), scale=True):
    fs, pxx = welch(x, fs=srate, nperseg=steps, scaling="density")
    band_powers = pxx
    if cut is not None:
        band_powers = band_powers[cut[0]:cut[1]]
    if scale:
        band_powers = np.log10(band_powers)
    return band_powers


def std_windowed(x):
    len_segm = int(len(x) / 4)
    stats = []
    for n in range(4):
        segm_data = x[n * len_segm:n * len_segm + len_segm]
        stats.extend([np.std(segm_data)])
    return stats


def abs_energy_windowed(x):
    len_segm = int(len(x) / 4)
    stats = []
    for n in range(4):
        segm_data = x[n * len_segm:n * len_segm + len_segm]
        stats.extend([np.sum(np.abs(segm_data))])
    return stats


def abs_max_windowed(x):
    len_segm = int(len(x) / 4)
    stats = []
    for n in range(4):
        segm_data = x[n * len_segm:n * len_segm + len_segm]
        stats.extend([np.max(np.abs(segm_data))])
    return stats


processing_pipeline = [bandpower, std_windowed, abs_energy_windowed, abs_max_windowed]


def feature_extraction_channel(x):
    """Extract features from a single channel (1D array of 976 timesteps). Returns 31 features."""
    features = []
    for func in processing_pipeline:
        result = func(x)
        if isinstance(result, np.ndarray):
            features.extend(result.tolist())
        else:
            features.extend(result)
    return features


# ============================================================
# Channel definitions
# ============================================================

TASKS = ["Relaxed1", "Relaxed2", "RelaxedTask1", "RelaxedTask2", "StretchHold",
         "HoldWeight", "DrinkGlas", "CrossArms", "TouchNose", "Entrainment1", "Entrainment2"]
DEVICE_LOCATIONS = ["LeftWrist", "RightWrist"]
SENSORS = ["Acceleration", "Rotation"]
AXES = ["X", "Y", "Z"]

# 31 feature names per channel
FEAT_PER_CHANNEL = 19 + 4 + 4 + 4  # bandpower + std + energy + max = 31

# Channel ordering: task x location x sensor x axis (132 channels)
# We group by (task x location x sensor) = 44 groups, each has 3 axes x 31 = 93 features
# But to keep it simpler: each (task x location x sensor x axis) = 1 channel with 31 features
# Grouping: (task x location x sensor) = 44 groups, each with 3 axes
# Token: 44 groups, each 31*3=93 dim? That's still big.
# Better: (task x location x sensor x axis) = 132 individual channels -> too many
# Best balance: (task x location x sensor) = 44 groups, average/concat axes
# Let's use 31*3=93 per group (concat X,Y,Z features)

def get_grouped_column_names():
    """Generate 44 grouped movement column names (task x location x sensor)."""
    columns = []
    for task in TASKS:
        for loc in DEVICE_LOCATIONS:
            for sensor in SENSORS:
                col = f"mov_{task}_{sensor[:3]}_{loc[0]}"
                columns.append(col)
    return columns


# ============================================================
# TOML generation
# ============================================================

def generate_toml(grouped_columns, n_features_per_group=93):
    """Generate TOML configuration file for PADS Phase 2 features."""
    lines = [
        "# PADS dataset configuration for nmed2024 Transformer (Phase 2: grouped tokens)",
        "# Auto-generated by convert_pads_data.py",
        "",
        "[features]",
        "",
        "# Demographics",
        "",
        '\t[feature.his_SEX]',
        '\ttype = "categorical"',
        '\tnum_categories = 2',
        "",
        '\t[feature.his_HANDED]',
        '\ttype = "categorical"',
        '\tnum_categories = 2',
        "",
        "# Physical measurements",
        "",
        '\t[feature.ph_AGE]',
        '\ttype = "numerical"',
        '\tshape = [1]',
        "",
        '\t[feature.ph_HEIGHT]',
        '\ttype = "numerical"',
        '\tshape = [1]',
        "",
        '\t[feature.ph_WEIGHT]',
        '\ttype = "numerical"',
        '\tshape = [1]',
        "",
        "# NMS Questionnaire (30 binary items)",
        "",
    ]
    for n in range(1, 31):
        lines.extend([
            f'\t[feature.nms_{n:02d}]',
            '\ttype = "categorical"',
            '\tnum_categories = 2',
            "",
        ])

    lines.append(f"# Movement features (44 grouped tokens, each {n_features_per_group}-dim)")
    lines.append("")
    for col in grouped_columns:
        lines.extend([
            f'\t[feature.{col}]',
            '\ttype = "numerical"',
            f'\tshape = [{n_features_per_group}]',
            "",
        ])

    lines.extend([
        "# Labels",
        "",
        "[labels]",
        "",
        '\t[label.HC]',
        '\ttype = "categorical"',
        '\tnum_categories = 2',
        "",
        '\t[label.PD]',
        '\ttype = "categorical"',
        '\tnum_categories = 2',
        "",
        '\t[label.DD]',
        '\ttype = "categorical"',
        '\tnum_categories = 2',
    ])
    return "\n".join(lines)


# ============================================================
# Main conversion
# ============================================================

def main():
    print("=" * 60)
    print("Converting PADS dataset to nmed2024 format (Phase 2: grouped)")
    print("=" * 60)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # 1. Load file list
    file_list = pd.read_csv(f"{PADS_ROOT}/file_list.csv")
    print(f"Total subjects: {len(file_list)}")
    print(f"Label distribution: {file_list['label'].value_counts().sort_index().to_dict()}")

    # 2. Generate grouped column names (44 groups)
    grouped_columns = get_grouped_column_names()
    print(f"Grouped movement tokens: {len(grouped_columns)}")

    # 3. Extract and group movement features
    print("\nExtracting and grouping movement features...")
    all_grouped_features = {col: [] for col in grouped_columns}

    for idx, row in file_list.iterrows():
        file_idx = row["id"]
        if idx % 50 == 0:
            print(f"  {idx + 1} / {len(file_list)}")

        data = np.fromfile(f"{PADS_ROOT}/movement/{file_idx:03d}_ml.bin",
                           dtype=np.float32).reshape((132, 976))

        # Channels are ordered: task x location x sensor x axis
        ch_idx = 0
        for task in TASKS:
            for loc in DEVICE_LOCATIONS:
                for sensor in SENSORS:
                    col = f"mov_{task}_{sensor[:3]}_{loc[0]}"
                    # Collect features from 3 axes (X, Y, Z) and concatenate
                    group_features = []
                    for axis in AXES:
                        ch_features = feature_extraction_channel(data[ch_idx])
                        group_features.extend(ch_features)
                        ch_idx += 1
                    # Store as list (will be converted to string in CSV)
                    all_grouped_features[col].append(group_features)

    # Build movement DataFrame with list values
    mov_df = pd.DataFrame(all_grouped_features)
    n_features_per_group = len(all_grouped_features[grouped_columns[0]][0])
    print(f"  Features per group: {n_features_per_group}")  # should be 93
    print(f"  Total groups: {len(grouped_columns)}")
    print(f"  Total tokens: {len(grouped_columns)} movement + 30 NMS + 5 demo = {len(grouped_columns) + 35}")

    # 4. Load questionnaire data
    print("\nLoading questionnaire data...")
    nms_columns = [f"nms_{n:02d}" for n in range(1, 31)]
    all_nms = []

    for idx, row in file_list.iterrows():
        file_idx = row["id"]
        data = np.fromfile(f"{PADS_ROOT}/questionnaire/{file_idx:03d}_ml.bin",
                           dtype=np.float32).reshape((30,))
        all_nms.append(data.astype(int).tolist())

    nms_df = pd.DataFrame(all_nms, columns=nms_columns)
    print(f"  Questionnaire shape: {nms_df.shape}")

    # 5. Demographics
    print("\nProcessing demographics...")
    demo_df = pd.DataFrame()
    demo_df["ID"] = file_list["id"].apply(lambda x: f"PADS_{x:03d}")
    demo_df["his_SEX"] = file_list["gender"].values
    demo_df["his_HANDED"] = file_list["handedness"].map({"right": 0, "left": 1})
    demo_df["ph_AGE"] = file_list["age"].values
    demo_df["ph_HEIGHT"] = file_list["height"].values
    demo_df["ph_WEIGHT"] = file_list["weight"].values

    # 6. Labels
    print("\nCreating labels...")
    label_df = pd.DataFrame()
    label_df["HC"] = (file_list["label"] == 0).astype(int)
    label_df["PD"] = (file_list["label"] == 1).astype(int)
    label_df["DD"] = (file_list["label"] == 2).astype(int)

    # 7. Combine all
    result_df = pd.concat([demo_df, nms_df, mov_df, label_df], axis=1)
    print(f"\nFinal dataset shape: {result_df.shape}")
    print(f"  Columns: {len(result_df.columns)} (ID + 5 demo + 30 NMS + {len(grouped_columns)} movement + 3 labels)")

    # 8. Save full dataset
    result_df.to_csv(f"{OUTPUT_DIR}/converted_pads.csv", index=False)
    print(f"Saved: {OUTPUT_DIR}/converted_pads.csv")

    # 9. Create train/val/test splits (70/10/20, stratified)
    print("\nCreating train/val/test splits...")
    labels = file_list["label"].values

    sss1 = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
    trainval_idx, test_idx = next(sss1.split(result_df, labels))

    sss2 = StratifiedShuffleSplit(n_splits=1, test_size=0.125, random_state=42)
    train_idx_rel, val_idx_rel = next(sss2.split(result_df.iloc[trainval_idx], labels[trainval_idx]))
    train_idx = trainval_idx[train_idx_rel]
    val_idx = trainval_idx[val_idx_rel]

    train_df = result_df.iloc[train_idx]
    val_df = result_df.iloc[val_idx]
    test_df = result_df.iloc[test_idx]

    for name, df in [("Train", train_df), ("Val", val_df), ("Test", test_df)]:
        print(f"  {name}: {len(df)} | HC={df['HC'].sum()} PD={df['PD'].sum()} DD={df['DD'].sum()}")

    train_df.to_csv(f"{OUTPUT_DIR}/train.csv", index=False)
    val_df.to_csv(f"{OUTPUT_DIR}/val.csv", index=False)
    test_df.to_csv(f"{OUTPUT_DIR}/test.csv", index=False)

    # 10. Generate TOML config
    print("\nGenerating TOML config...")
    toml_content = generate_toml(grouped_columns, n_features_per_group)
    toml_path = f"{TOML_DIR}/pads_conf.toml"
    with open(toml_path, "w") as f:
        f.write(toml_content)
    print(f"Saved: {toml_path}")

    print("\n" + "=" * 60)
    print("Phase 2 conversion complete!")
    print(f"  Tokens: {len(grouped_columns)} movement + 30 NMS + 5 demo = {len(grouped_columns) + 35}")
    print(f"  Each movement token: {n_features_per_group}-dim (3 axes x 31 features)")
    print("=" * 60)


if __name__ == "__main__":
    main()
